---
- hosts: ec2
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest update_cache=yes
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: remove old site files
      file:
        state: absent
        path: /var/www/html/
      become: yes
    - name: copy the static site to www
      copy:
        src: ~/WebstormProjects/drabriw/
        dest: /var/www/html/
      become: yes
    - name: restart nginx
      service:
        name=nginx
        state=restarted
      become: yes